// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/ffddorf/unms-api-go/models"
)

// GetNmsSettingsReader is a Reader for the GetNmsSettings structure.
type GetNmsSettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNmsSettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNmsSettingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetNmsSettingsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetNmsSettingsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetNmsSettingsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNmsSettingsOK creates a GetNmsSettingsOK with default headers values
func NewGetNmsSettingsOK() *GetNmsSettingsOK {
	return &GetNmsSettingsOK{}
}

/*GetNmsSettingsOK handles this case with default header values.

Successful
*/
type GetNmsSettingsOK struct {
	Payload *models.NmsSettings1
}

func (o *GetNmsSettingsOK) Error() string {
	return fmt.Sprintf("[GET /nms/settings][%d] getNmsSettingsOK  %+v", 200, o.Payload)
}

func (o *GetNmsSettingsOK) GetPayload() *models.NmsSettings1 {
	return o.Payload
}

func (o *GetNmsSettingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NmsSettings1)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNmsSettingsUnauthorized creates a GetNmsSettingsUnauthorized with default headers values
func NewGetNmsSettingsUnauthorized() *GetNmsSettingsUnauthorized {
	return &GetNmsSettingsUnauthorized{}
}

/*GetNmsSettingsUnauthorized handles this case with default header values.

Unauthorized
*/
type GetNmsSettingsUnauthorized struct {
	Payload *models.Error
}

func (o *GetNmsSettingsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /nms/settings][%d] getNmsSettingsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetNmsSettingsUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetNmsSettingsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNmsSettingsForbidden creates a GetNmsSettingsForbidden with default headers values
func NewGetNmsSettingsForbidden() *GetNmsSettingsForbidden {
	return &GetNmsSettingsForbidden{}
}

/*GetNmsSettingsForbidden handles this case with default header values.

Forbidden
*/
type GetNmsSettingsForbidden struct {
	Payload *models.Error
}

func (o *GetNmsSettingsForbidden) Error() string {
	return fmt.Sprintf("[GET /nms/settings][%d] getNmsSettingsForbidden  %+v", 403, o.Payload)
}

func (o *GetNmsSettingsForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetNmsSettingsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNmsSettingsInternalServerError creates a GetNmsSettingsInternalServerError with default headers values
func NewGetNmsSettingsInternalServerError() *GetNmsSettingsInternalServerError {
	return &GetNmsSettingsInternalServerError{}
}

/*GetNmsSettingsInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetNmsSettingsInternalServerError struct {
	Payload *models.Error
}

func (o *GetNmsSettingsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /nms/settings][%d] getNmsSettingsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetNmsSettingsInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetNmsSettingsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
