// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/ffddorf/unms-api-go/models"
)

// DeleteDevicesDeviceidBackupsBackupidReader is a Reader for the DeleteDevicesDeviceidBackupsBackupid structure.
type DeleteDevicesDeviceidBackupsBackupidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDevicesDeviceidBackupsBackupidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteDevicesDeviceidBackupsBackupidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteDevicesDeviceidBackupsBackupidBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteDevicesDeviceidBackupsBackupidUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteDevicesDeviceidBackupsBackupidForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteDevicesDeviceidBackupsBackupidNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteDevicesDeviceidBackupsBackupidInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteDevicesDeviceidBackupsBackupidOK creates a DeleteDevicesDeviceidBackupsBackupidOK with default headers values
func NewDeleteDevicesDeviceidBackupsBackupidOK() *DeleteDevicesDeviceidBackupsBackupidOK {
	return &DeleteDevicesDeviceidBackupsBackupidOK{}
}

/*DeleteDevicesDeviceidBackupsBackupidOK handles this case with default header values.

Successful
*/
type DeleteDevicesDeviceidBackupsBackupidOK struct {
	Payload *models.Status
}

func (o *DeleteDevicesDeviceidBackupsBackupidOK) Error() string {
	return fmt.Sprintf("[DELETE /devices/{deviceId}/backups/{backupId}][%d] deleteDevicesDeviceidBackupsBackupidOK  %+v", 200, o.Payload)
}

func (o *DeleteDevicesDeviceidBackupsBackupidOK) GetPayload() *models.Status {
	return o.Payload
}

func (o *DeleteDevicesDeviceidBackupsBackupidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDevicesDeviceidBackupsBackupidBadRequest creates a DeleteDevicesDeviceidBackupsBackupidBadRequest with default headers values
func NewDeleteDevicesDeviceidBackupsBackupidBadRequest() *DeleteDevicesDeviceidBackupsBackupidBadRequest {
	return &DeleteDevicesDeviceidBackupsBackupidBadRequest{}
}

/*DeleteDevicesDeviceidBackupsBackupidBadRequest handles this case with default header values.

Bad Request
*/
type DeleteDevicesDeviceidBackupsBackupidBadRequest struct {
	Payload *models.Error
}

func (o *DeleteDevicesDeviceidBackupsBackupidBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /devices/{deviceId}/backups/{backupId}][%d] deleteDevicesDeviceidBackupsBackupidBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteDevicesDeviceidBackupsBackupidBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteDevicesDeviceidBackupsBackupidBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDevicesDeviceidBackupsBackupidUnauthorized creates a DeleteDevicesDeviceidBackupsBackupidUnauthorized with default headers values
func NewDeleteDevicesDeviceidBackupsBackupidUnauthorized() *DeleteDevicesDeviceidBackupsBackupidUnauthorized {
	return &DeleteDevicesDeviceidBackupsBackupidUnauthorized{}
}

/*DeleteDevicesDeviceidBackupsBackupidUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteDevicesDeviceidBackupsBackupidUnauthorized struct {
	Payload *models.Error
}

func (o *DeleteDevicesDeviceidBackupsBackupidUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /devices/{deviceId}/backups/{backupId}][%d] deleteDevicesDeviceidBackupsBackupidUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteDevicesDeviceidBackupsBackupidUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteDevicesDeviceidBackupsBackupidUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDevicesDeviceidBackupsBackupidForbidden creates a DeleteDevicesDeviceidBackupsBackupidForbidden with default headers values
func NewDeleteDevicesDeviceidBackupsBackupidForbidden() *DeleteDevicesDeviceidBackupsBackupidForbidden {
	return &DeleteDevicesDeviceidBackupsBackupidForbidden{}
}

/*DeleteDevicesDeviceidBackupsBackupidForbidden handles this case with default header values.

Forbidden
*/
type DeleteDevicesDeviceidBackupsBackupidForbidden struct {
	Payload *models.Error
}

func (o *DeleteDevicesDeviceidBackupsBackupidForbidden) Error() string {
	return fmt.Sprintf("[DELETE /devices/{deviceId}/backups/{backupId}][%d] deleteDevicesDeviceidBackupsBackupidForbidden  %+v", 403, o.Payload)
}

func (o *DeleteDevicesDeviceidBackupsBackupidForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteDevicesDeviceidBackupsBackupidForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDevicesDeviceidBackupsBackupidNotFound creates a DeleteDevicesDeviceidBackupsBackupidNotFound with default headers values
func NewDeleteDevicesDeviceidBackupsBackupidNotFound() *DeleteDevicesDeviceidBackupsBackupidNotFound {
	return &DeleteDevicesDeviceidBackupsBackupidNotFound{}
}

/*DeleteDevicesDeviceidBackupsBackupidNotFound handles this case with default header values.

Not Found
*/
type DeleteDevicesDeviceidBackupsBackupidNotFound struct {
	Payload *models.Error
}

func (o *DeleteDevicesDeviceidBackupsBackupidNotFound) Error() string {
	return fmt.Sprintf("[DELETE /devices/{deviceId}/backups/{backupId}][%d] deleteDevicesDeviceidBackupsBackupidNotFound  %+v", 404, o.Payload)
}

func (o *DeleteDevicesDeviceidBackupsBackupidNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteDevicesDeviceidBackupsBackupidNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDevicesDeviceidBackupsBackupidInternalServerError creates a DeleteDevicesDeviceidBackupsBackupidInternalServerError with default headers values
func NewDeleteDevicesDeviceidBackupsBackupidInternalServerError() *DeleteDevicesDeviceidBackupsBackupidInternalServerError {
	return &DeleteDevicesDeviceidBackupsBackupidInternalServerError{}
}

/*DeleteDevicesDeviceidBackupsBackupidInternalServerError handles this case with default header values.

Internal Server Error
*/
type DeleteDevicesDeviceidBackupsBackupidInternalServerError struct {
	Payload *models.Error
}

func (o *DeleteDevicesDeviceidBackupsBackupidInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /devices/{deviceId}/backups/{backupId}][%d] deleteDevicesDeviceidBackupsBackupidInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteDevicesDeviceidBackupsBackupidInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteDevicesDeviceidBackupsBackupidInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
