// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDevicesAirmaxesIDSitesurveyParams creates a new GetDevicesAirmaxesIDSitesurveyParams object
// with the default values initialized.
func NewGetDevicesAirmaxesIDSitesurveyParams() *GetDevicesAirmaxesIDSitesurveyParams {
	var ()
	return &GetDevicesAirmaxesIDSitesurveyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDevicesAirmaxesIDSitesurveyParamsWithTimeout creates a new GetDevicesAirmaxesIDSitesurveyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDevicesAirmaxesIDSitesurveyParamsWithTimeout(timeout time.Duration) *GetDevicesAirmaxesIDSitesurveyParams {
	var ()
	return &GetDevicesAirmaxesIDSitesurveyParams{

		timeout: timeout,
	}
}

// NewGetDevicesAirmaxesIDSitesurveyParamsWithContext creates a new GetDevicesAirmaxesIDSitesurveyParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDevicesAirmaxesIDSitesurveyParamsWithContext(ctx context.Context) *GetDevicesAirmaxesIDSitesurveyParams {
	var ()
	return &GetDevicesAirmaxesIDSitesurveyParams{

		Context: ctx,
	}
}

// NewGetDevicesAirmaxesIDSitesurveyParamsWithHTTPClient creates a new GetDevicesAirmaxesIDSitesurveyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDevicesAirmaxesIDSitesurveyParamsWithHTTPClient(client *http.Client) *GetDevicesAirmaxesIDSitesurveyParams {
	var ()
	return &GetDevicesAirmaxesIDSitesurveyParams{
		HTTPClient: client,
	}
}

/*GetDevicesAirmaxesIDSitesurveyParams contains all the parameters to send to the API endpoint
for the get devices airmaxes Id sitesurvey operation typically these are written to a http.Request
*/
type GetDevicesAirmaxesIDSitesurveyParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get devices airmaxes Id sitesurvey params
func (o *GetDevicesAirmaxesIDSitesurveyParams) WithTimeout(timeout time.Duration) *GetDevicesAirmaxesIDSitesurveyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get devices airmaxes Id sitesurvey params
func (o *GetDevicesAirmaxesIDSitesurveyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get devices airmaxes Id sitesurvey params
func (o *GetDevicesAirmaxesIDSitesurveyParams) WithContext(ctx context.Context) *GetDevicesAirmaxesIDSitesurveyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get devices airmaxes Id sitesurvey params
func (o *GetDevicesAirmaxesIDSitesurveyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get devices airmaxes Id sitesurvey params
func (o *GetDevicesAirmaxesIDSitesurveyParams) WithHTTPClient(client *http.Client) *GetDevicesAirmaxesIDSitesurveyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get devices airmaxes Id sitesurvey params
func (o *GetDevicesAirmaxesIDSitesurveyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get devices airmaxes Id sitesurvey params
func (o *GetDevicesAirmaxesIDSitesurveyParams) WithID(id string) *GetDevicesAirmaxesIDSitesurveyParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get devices airmaxes Id sitesurvey params
func (o *GetDevicesAirmaxesIDSitesurveyParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetDevicesAirmaxesIDSitesurveyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
