// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostDevicesIDBackupsParams creates a new PostDevicesIDBackupsParams object
// with the default values initialized.
func NewPostDevicesIDBackupsParams() *PostDevicesIDBackupsParams {
	var ()
	return &PostDevicesIDBackupsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostDevicesIDBackupsParamsWithTimeout creates a new PostDevicesIDBackupsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostDevicesIDBackupsParamsWithTimeout(timeout time.Duration) *PostDevicesIDBackupsParams {
	var ()
	return &PostDevicesIDBackupsParams{

		timeout: timeout,
	}
}

// NewPostDevicesIDBackupsParamsWithContext creates a new PostDevicesIDBackupsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostDevicesIDBackupsParamsWithContext(ctx context.Context) *PostDevicesIDBackupsParams {
	var ()
	return &PostDevicesIDBackupsParams{

		Context: ctx,
	}
}

// NewPostDevicesIDBackupsParamsWithHTTPClient creates a new PostDevicesIDBackupsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostDevicesIDBackupsParamsWithHTTPClient(client *http.Client) *PostDevicesIDBackupsParams {
	var ()
	return &PostDevicesIDBackupsParams{
		HTTPClient: client,
	}
}

/*PostDevicesIDBackupsParams contains all the parameters to send to the API endpoint
for the post devices Id backups operation typically these are written to a http.Request
*/
type PostDevicesIDBackupsParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post devices Id backups params
func (o *PostDevicesIDBackupsParams) WithTimeout(timeout time.Duration) *PostDevicesIDBackupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post devices Id backups params
func (o *PostDevicesIDBackupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post devices Id backups params
func (o *PostDevicesIDBackupsParams) WithContext(ctx context.Context) *PostDevicesIDBackupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post devices Id backups params
func (o *PostDevicesIDBackupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post devices Id backups params
func (o *PostDevicesIDBackupsParams) WithHTTPClient(client *http.Client) *PostDevicesIDBackupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post devices Id backups params
func (o *PostDevicesIDBackupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the post devices Id backups params
func (o *PostDevicesIDBackupsParams) WithID(id string) *PostDevicesIDBackupsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post devices Id backups params
func (o *PostDevicesIDBackupsParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostDevicesIDBackupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
