// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/ffddorf/unms-api-go/models"
)

// PostDevicesDeviceidInterfacesPppoeReader is a Reader for the PostDevicesDeviceidInterfacesPppoe structure.
type PostDevicesDeviceidInterfacesPppoeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDevicesDeviceidInterfacesPppoeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostDevicesDeviceidInterfacesPppoeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostDevicesDeviceidInterfacesPppoeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostDevicesDeviceidInterfacesPppoeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostDevicesDeviceidInterfacesPppoeForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostDevicesDeviceidInterfacesPppoeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostDevicesDeviceidInterfacesPppoeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostDevicesDeviceidInterfacesPppoeOK creates a PostDevicesDeviceidInterfacesPppoeOK with default headers values
func NewPostDevicesDeviceidInterfacesPppoeOK() *PostDevicesDeviceidInterfacesPppoeOK {
	return &PostDevicesDeviceidInterfacesPppoeOK{}
}

/*PostDevicesDeviceidInterfacesPppoeOK handles this case with default header values.

Successful
*/
type PostDevicesDeviceidInterfacesPppoeOK struct {
	Payload *models.DeviceInterfaceSchema
}

func (o *PostDevicesDeviceidInterfacesPppoeOK) Error() string {
	return fmt.Sprintf("[POST /devices/{deviceId}/interfaces/pppoe][%d] postDevicesDeviceidInterfacesPppoeOK  %+v", 200, o.Payload)
}

func (o *PostDevicesDeviceidInterfacesPppoeOK) GetPayload() *models.DeviceInterfaceSchema {
	return o.Payload
}

func (o *PostDevicesDeviceidInterfacesPppoeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeviceInterfaceSchema)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDevicesDeviceidInterfacesPppoeBadRequest creates a PostDevicesDeviceidInterfacesPppoeBadRequest with default headers values
func NewPostDevicesDeviceidInterfacesPppoeBadRequest() *PostDevicesDeviceidInterfacesPppoeBadRequest {
	return &PostDevicesDeviceidInterfacesPppoeBadRequest{}
}

/*PostDevicesDeviceidInterfacesPppoeBadRequest handles this case with default header values.

Bad Request
*/
type PostDevicesDeviceidInterfacesPppoeBadRequest struct {
	Payload *models.Error
}

func (o *PostDevicesDeviceidInterfacesPppoeBadRequest) Error() string {
	return fmt.Sprintf("[POST /devices/{deviceId}/interfaces/pppoe][%d] postDevicesDeviceidInterfacesPppoeBadRequest  %+v", 400, o.Payload)
}

func (o *PostDevicesDeviceidInterfacesPppoeBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostDevicesDeviceidInterfacesPppoeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDevicesDeviceidInterfacesPppoeUnauthorized creates a PostDevicesDeviceidInterfacesPppoeUnauthorized with default headers values
func NewPostDevicesDeviceidInterfacesPppoeUnauthorized() *PostDevicesDeviceidInterfacesPppoeUnauthorized {
	return &PostDevicesDeviceidInterfacesPppoeUnauthorized{}
}

/*PostDevicesDeviceidInterfacesPppoeUnauthorized handles this case with default header values.

Unauthorized
*/
type PostDevicesDeviceidInterfacesPppoeUnauthorized struct {
	Payload *models.Error
}

func (o *PostDevicesDeviceidInterfacesPppoeUnauthorized) Error() string {
	return fmt.Sprintf("[POST /devices/{deviceId}/interfaces/pppoe][%d] postDevicesDeviceidInterfacesPppoeUnauthorized  %+v", 401, o.Payload)
}

func (o *PostDevicesDeviceidInterfacesPppoeUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostDevicesDeviceidInterfacesPppoeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDevicesDeviceidInterfacesPppoeForbidden creates a PostDevicesDeviceidInterfacesPppoeForbidden with default headers values
func NewPostDevicesDeviceidInterfacesPppoeForbidden() *PostDevicesDeviceidInterfacesPppoeForbidden {
	return &PostDevicesDeviceidInterfacesPppoeForbidden{}
}

/*PostDevicesDeviceidInterfacesPppoeForbidden handles this case with default header values.

Forbidden
*/
type PostDevicesDeviceidInterfacesPppoeForbidden struct {
	Payload *models.Error
}

func (o *PostDevicesDeviceidInterfacesPppoeForbidden) Error() string {
	return fmt.Sprintf("[POST /devices/{deviceId}/interfaces/pppoe][%d] postDevicesDeviceidInterfacesPppoeForbidden  %+v", 403, o.Payload)
}

func (o *PostDevicesDeviceidInterfacesPppoeForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostDevicesDeviceidInterfacesPppoeForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDevicesDeviceidInterfacesPppoeNotFound creates a PostDevicesDeviceidInterfacesPppoeNotFound with default headers values
func NewPostDevicesDeviceidInterfacesPppoeNotFound() *PostDevicesDeviceidInterfacesPppoeNotFound {
	return &PostDevicesDeviceidInterfacesPppoeNotFound{}
}

/*PostDevicesDeviceidInterfacesPppoeNotFound handles this case with default header values.

Not Found
*/
type PostDevicesDeviceidInterfacesPppoeNotFound struct {
	Payload *models.Error
}

func (o *PostDevicesDeviceidInterfacesPppoeNotFound) Error() string {
	return fmt.Sprintf("[POST /devices/{deviceId}/interfaces/pppoe][%d] postDevicesDeviceidInterfacesPppoeNotFound  %+v", 404, o.Payload)
}

func (o *PostDevicesDeviceidInterfacesPppoeNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostDevicesDeviceidInterfacesPppoeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDevicesDeviceidInterfacesPppoeInternalServerError creates a PostDevicesDeviceidInterfacesPppoeInternalServerError with default headers values
func NewPostDevicesDeviceidInterfacesPppoeInternalServerError() *PostDevicesDeviceidInterfacesPppoeInternalServerError {
	return &PostDevicesDeviceidInterfacesPppoeInternalServerError{}
}

/*PostDevicesDeviceidInterfacesPppoeInternalServerError handles this case with default header values.

Internal Server Error
*/
type PostDevicesDeviceidInterfacesPppoeInternalServerError struct {
	Payload *models.Error
}

func (o *PostDevicesDeviceidInterfacesPppoeInternalServerError) Error() string {
	return fmt.Sprintf("[POST /devices/{deviceId}/interfaces/pppoe][%d] postDevicesDeviceidInterfacesPppoeInternalServerError  %+v", 500, o.Payload)
}

func (o *PostDevicesDeviceidInterfacesPppoeInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostDevicesDeviceidInterfacesPppoeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
