// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutDevicesDeviceidInterfacesInterfacenameParams creates a new PutDevicesDeviceidInterfacesInterfacenameParams object
// with the default values initialized.
func NewPutDevicesDeviceidInterfacesInterfacenameParams() *PutDevicesDeviceidInterfacesInterfacenameParams {
	var ()
	return &PutDevicesDeviceidInterfacesInterfacenameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutDevicesDeviceidInterfacesInterfacenameParamsWithTimeout creates a new PutDevicesDeviceidInterfacesInterfacenameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutDevicesDeviceidInterfacesInterfacenameParamsWithTimeout(timeout time.Duration) *PutDevicesDeviceidInterfacesInterfacenameParams {
	var ()
	return &PutDevicesDeviceidInterfacesInterfacenameParams{

		timeout: timeout,
	}
}

// NewPutDevicesDeviceidInterfacesInterfacenameParamsWithContext creates a new PutDevicesDeviceidInterfacesInterfacenameParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutDevicesDeviceidInterfacesInterfacenameParamsWithContext(ctx context.Context) *PutDevicesDeviceidInterfacesInterfacenameParams {
	var ()
	return &PutDevicesDeviceidInterfacesInterfacenameParams{

		Context: ctx,
	}
}

// NewPutDevicesDeviceidInterfacesInterfacenameParamsWithHTTPClient creates a new PutDevicesDeviceidInterfacesInterfacenameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutDevicesDeviceidInterfacesInterfacenameParamsWithHTTPClient(client *http.Client) *PutDevicesDeviceidInterfacesInterfacenameParams {
	var ()
	return &PutDevicesDeviceidInterfacesInterfacenameParams{
		HTTPClient: client,
	}
}

/*PutDevicesDeviceidInterfacesInterfacenameParams contains all the parameters to send to the API endpoint
for the put devices deviceid interfaces interfacename operation typically these are written to a http.Request
*/
type PutDevicesDeviceidInterfacesInterfacenameParams struct {

	/*DeviceID*/
	DeviceID string
	/*InterfaceName*/
	InterfaceName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put devices deviceid interfaces interfacename params
func (o *PutDevicesDeviceidInterfacesInterfacenameParams) WithTimeout(timeout time.Duration) *PutDevicesDeviceidInterfacesInterfacenameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put devices deviceid interfaces interfacename params
func (o *PutDevicesDeviceidInterfacesInterfacenameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put devices deviceid interfaces interfacename params
func (o *PutDevicesDeviceidInterfacesInterfacenameParams) WithContext(ctx context.Context) *PutDevicesDeviceidInterfacesInterfacenameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put devices deviceid interfaces interfacename params
func (o *PutDevicesDeviceidInterfacesInterfacenameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put devices deviceid interfaces interfacename params
func (o *PutDevicesDeviceidInterfacesInterfacenameParams) WithHTTPClient(client *http.Client) *PutDevicesDeviceidInterfacesInterfacenameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put devices deviceid interfaces interfacename params
func (o *PutDevicesDeviceidInterfacesInterfacenameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceID adds the deviceID to the put devices deviceid interfaces interfacename params
func (o *PutDevicesDeviceidInterfacesInterfacenameParams) WithDeviceID(deviceID string) *PutDevicesDeviceidInterfacesInterfacenameParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the put devices deviceid interfaces interfacename params
func (o *PutDevicesDeviceidInterfacesInterfacenameParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WithInterfaceName adds the interfaceName to the put devices deviceid interfaces interfacename params
func (o *PutDevicesDeviceidInterfacesInterfacenameParams) WithInterfaceName(interfaceName string) *PutDevicesDeviceidInterfacesInterfacenameParams {
	o.SetInterfaceName(interfaceName)
	return o
}

// SetInterfaceName adds the interfaceName to the put devices deviceid interfaces interfacename params
func (o *PutDevicesDeviceidInterfacesInterfacenameParams) SetInterfaceName(interfaceName string) {
	o.InterfaceName = interfaceName
}

// WriteToRequest writes these params to a swagger request
func (o *PutDevicesDeviceidInterfacesInterfacenameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param deviceId
	if err := r.SetPathParam("deviceId", o.DeviceID); err != nil {
		return err
	}

	// path param interfaceName
	if err := r.SetPathParam("interfaceName", o.InterfaceName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
