// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/ffddorf/unms-api-go/models"
)

// PutDevicesOnusIDWirelessReader is a Reader for the PutDevicesOnusIDWireless structure.
type PutDevicesOnusIDWirelessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutDevicesOnusIDWirelessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutDevicesOnusIDWirelessOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutDevicesOnusIDWirelessBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPutDevicesOnusIDWirelessUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPutDevicesOnusIDWirelessForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutDevicesOnusIDWirelessNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutDevicesOnusIDWirelessInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutDevicesOnusIDWirelessOK creates a PutDevicesOnusIDWirelessOK with default headers values
func NewPutDevicesOnusIDWirelessOK() *PutDevicesOnusIDWirelessOK {
	return &PutDevicesOnusIDWirelessOK{}
}

/*PutDevicesOnusIDWirelessOK handles this case with default header values.

Successful
*/
type PutDevicesOnusIDWirelessOK struct {
	Payload *models.OnuWireless
}

func (o *PutDevicesOnusIDWirelessOK) Error() string {
	return fmt.Sprintf("[PUT /devices/onus/{id}/wireless][%d] putDevicesOnusIdWirelessOK  %+v", 200, o.Payload)
}

func (o *PutDevicesOnusIDWirelessOK) GetPayload() *models.OnuWireless {
	return o.Payload
}

func (o *PutDevicesOnusIDWirelessOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OnuWireless)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutDevicesOnusIDWirelessBadRequest creates a PutDevicesOnusIDWirelessBadRequest with default headers values
func NewPutDevicesOnusIDWirelessBadRequest() *PutDevicesOnusIDWirelessBadRequest {
	return &PutDevicesOnusIDWirelessBadRequest{}
}

/*PutDevicesOnusIDWirelessBadRequest handles this case with default header values.

Bad Request
*/
type PutDevicesOnusIDWirelessBadRequest struct {
	Payload *models.Error
}

func (o *PutDevicesOnusIDWirelessBadRequest) Error() string {
	return fmt.Sprintf("[PUT /devices/onus/{id}/wireless][%d] putDevicesOnusIdWirelessBadRequest  %+v", 400, o.Payload)
}

func (o *PutDevicesOnusIDWirelessBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PutDevicesOnusIDWirelessBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutDevicesOnusIDWirelessUnauthorized creates a PutDevicesOnusIDWirelessUnauthorized with default headers values
func NewPutDevicesOnusIDWirelessUnauthorized() *PutDevicesOnusIDWirelessUnauthorized {
	return &PutDevicesOnusIDWirelessUnauthorized{}
}

/*PutDevicesOnusIDWirelessUnauthorized handles this case with default header values.

Unauthorized
*/
type PutDevicesOnusIDWirelessUnauthorized struct {
	Payload *models.Error
}

func (o *PutDevicesOnusIDWirelessUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /devices/onus/{id}/wireless][%d] putDevicesOnusIdWirelessUnauthorized  %+v", 401, o.Payload)
}

func (o *PutDevicesOnusIDWirelessUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PutDevicesOnusIDWirelessUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutDevicesOnusIDWirelessForbidden creates a PutDevicesOnusIDWirelessForbidden with default headers values
func NewPutDevicesOnusIDWirelessForbidden() *PutDevicesOnusIDWirelessForbidden {
	return &PutDevicesOnusIDWirelessForbidden{}
}

/*PutDevicesOnusIDWirelessForbidden handles this case with default header values.

Forbidden
*/
type PutDevicesOnusIDWirelessForbidden struct {
	Payload *models.Error
}

func (o *PutDevicesOnusIDWirelessForbidden) Error() string {
	return fmt.Sprintf("[PUT /devices/onus/{id}/wireless][%d] putDevicesOnusIdWirelessForbidden  %+v", 403, o.Payload)
}

func (o *PutDevicesOnusIDWirelessForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *PutDevicesOnusIDWirelessForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutDevicesOnusIDWirelessNotFound creates a PutDevicesOnusIDWirelessNotFound with default headers values
func NewPutDevicesOnusIDWirelessNotFound() *PutDevicesOnusIDWirelessNotFound {
	return &PutDevicesOnusIDWirelessNotFound{}
}

/*PutDevicesOnusIDWirelessNotFound handles this case with default header values.

Not Found
*/
type PutDevicesOnusIDWirelessNotFound struct {
	Payload *models.Error
}

func (o *PutDevicesOnusIDWirelessNotFound) Error() string {
	return fmt.Sprintf("[PUT /devices/onus/{id}/wireless][%d] putDevicesOnusIdWirelessNotFound  %+v", 404, o.Payload)
}

func (o *PutDevicesOnusIDWirelessNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *PutDevicesOnusIDWirelessNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutDevicesOnusIDWirelessInternalServerError creates a PutDevicesOnusIDWirelessInternalServerError with default headers values
func NewPutDevicesOnusIDWirelessInternalServerError() *PutDevicesOnusIDWirelessInternalServerError {
	return &PutDevicesOnusIDWirelessInternalServerError{}
}

/*PutDevicesOnusIDWirelessInternalServerError handles this case with default header values.

Internal Server Error
*/
type PutDevicesOnusIDWirelessInternalServerError struct {
	Payload *models.Error
}

func (o *PutDevicesOnusIDWirelessInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /devices/onus/{id}/wireless][%d] putDevicesOnusIdWirelessInternalServerError  %+v", 500, o.Payload)
}

func (o *PutDevicesOnusIDWirelessInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PutDevicesOnusIDWirelessInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
