/*
 * UNMS API
 *
 * You can authorize calls with x-auth-token by clicking the button on the right, to not have to fill in authorization token for each request. Entered value in authorization token for a request, will be replaced by the one entered in authorization. To get this token use /user/login request.
 *
 * API version: 2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package unms

// Device statistics + statistics for all interfaces
type DeviceStatistics struct {
	// Number of milliseconds between data points
	Period float32 `json:"period,omitempty"`

	Interval *NmsStatisticsInterval `json:"interval,omitempty"`

	Ram *GraphDataSet `json:"ram,omitempty"`

	Cpu *GraphDataSet `json:"cpu,omitempty"`

	Ping *GraphDataSet `json:"ping,omitempty"`

	Errors *GraphDataSet `json:"errors,omitempty"`

	Interfaces []DeviceStatisticsInterfaces `json:"interfaces,omitempty"`
}
