// Code generated by go-swagger; DO NOT EDIT.

package data_links

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/ffddorf/unms-api-go/models"
)

// NewPostDatalinksParams creates a new PostDatalinksParams object
// with the default values initialized.
func NewPostDatalinksParams() *PostDatalinksParams {
	var ()
	return &PostDatalinksParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostDatalinksParamsWithTimeout creates a new PostDatalinksParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostDatalinksParamsWithTimeout(timeout time.Duration) *PostDatalinksParams {
	var ()
	return &PostDatalinksParams{

		timeout: timeout,
	}
}

// NewPostDatalinksParamsWithContext creates a new PostDatalinksParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostDatalinksParamsWithContext(ctx context.Context) *PostDatalinksParams {
	var ()
	return &PostDatalinksParams{

		Context: ctx,
	}
}

// NewPostDatalinksParamsWithHTTPClient creates a new PostDatalinksParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostDatalinksParamsWithHTTPClient(client *http.Client) *PostDatalinksParams {
	var ()
	return &PostDatalinksParams{
		HTTPClient: client,
	}
}

/*PostDatalinksParams contains all the parameters to send to the API endpoint
for the post datalinks operation typically these are written to a http.Request
*/
type PostDatalinksParams struct {

	/*Body*/
	Body *models.DataLinkPayload

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post datalinks params
func (o *PostDatalinksParams) WithTimeout(timeout time.Duration) *PostDatalinksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post datalinks params
func (o *PostDatalinksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post datalinks params
func (o *PostDatalinksParams) WithContext(ctx context.Context) *PostDatalinksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post datalinks params
func (o *PostDatalinksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post datalinks params
func (o *PostDatalinksParams) WithHTTPClient(client *http.Client) *PostDatalinksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post datalinks params
func (o *PostDatalinksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post datalinks params
func (o *PostDatalinksParams) WithBody(body *models.DataLinkPayload) *PostDatalinksParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post datalinks params
func (o *PostDatalinksParams) SetBody(body *models.DataLinkPayload) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostDatalinksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
