// Code generated by go-swagger; DO NOT EDIT.

package authorization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/ffddorf/unms-api-go/models"
)

// PostUserPasswordResetReader is a Reader for the PostUserPasswordReset structure.
type PostUserPasswordResetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostUserPasswordResetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostUserPasswordResetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostUserPasswordResetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostUserPasswordResetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostUserPasswordResetInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostUserPasswordResetOK creates a PostUserPasswordResetOK with default headers values
func NewPostUserPasswordResetOK() *PostUserPasswordResetOK {
	return &PostUserPasswordResetOK{}
}

/*PostUserPasswordResetOK handles this case with default header values.

Successful
*/
type PostUserPasswordResetOK struct {
	Payload *models.Status
}

func (o *PostUserPasswordResetOK) Error() string {
	return fmt.Sprintf("[POST /user/password/reset][%d] postUserPasswordResetOK  %+v", 200, o.Payload)
}

func (o *PostUserPasswordResetOK) GetPayload() *models.Status {
	return o.Payload
}

func (o *PostUserPasswordResetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostUserPasswordResetBadRequest creates a PostUserPasswordResetBadRequest with default headers values
func NewPostUserPasswordResetBadRequest() *PostUserPasswordResetBadRequest {
	return &PostUserPasswordResetBadRequest{}
}

/*PostUserPasswordResetBadRequest handles this case with default header values.

Bad Request
*/
type PostUserPasswordResetBadRequest struct {
	Payload *models.Error
}

func (o *PostUserPasswordResetBadRequest) Error() string {
	return fmt.Sprintf("[POST /user/password/reset][%d] postUserPasswordResetBadRequest  %+v", 400, o.Payload)
}

func (o *PostUserPasswordResetBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostUserPasswordResetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostUserPasswordResetUnauthorized creates a PostUserPasswordResetUnauthorized with default headers values
func NewPostUserPasswordResetUnauthorized() *PostUserPasswordResetUnauthorized {
	return &PostUserPasswordResetUnauthorized{}
}

/*PostUserPasswordResetUnauthorized handles this case with default header values.

Unauthorized
*/
type PostUserPasswordResetUnauthorized struct {
	Payload *models.Error
}

func (o *PostUserPasswordResetUnauthorized) Error() string {
	return fmt.Sprintf("[POST /user/password/reset][%d] postUserPasswordResetUnauthorized  %+v", 401, o.Payload)
}

func (o *PostUserPasswordResetUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostUserPasswordResetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostUserPasswordResetInternalServerError creates a PostUserPasswordResetInternalServerError with default headers values
func NewPostUserPasswordResetInternalServerError() *PostUserPasswordResetInternalServerError {
	return &PostUserPasswordResetInternalServerError{}
}

/*PostUserPasswordResetInternalServerError handles this case with default header values.

Internal Server Error
*/
type PostUserPasswordResetInternalServerError struct {
	Payload *models.Error
}

func (o *PostUserPasswordResetInternalServerError) Error() string {
	return fmt.Sprintf("[POST /user/password/reset][%d] postUserPasswordResetInternalServerError  %+v", 500, o.Payload)
}

func (o *PostUserPasswordResetInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostUserPasswordResetInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
