// Code generated by go-swagger; DO NOT EDIT.

package authorization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostUserChecksessionParams creates a new PostUserChecksessionParams object
// with the default values initialized.
func NewPostUserChecksessionParams() *PostUserChecksessionParams {

	return &PostUserChecksessionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostUserChecksessionParamsWithTimeout creates a new PostUserChecksessionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostUserChecksessionParamsWithTimeout(timeout time.Duration) *PostUserChecksessionParams {

	return &PostUserChecksessionParams{

		timeout: timeout,
	}
}

// NewPostUserChecksessionParamsWithContext creates a new PostUserChecksessionParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostUserChecksessionParamsWithContext(ctx context.Context) *PostUserChecksessionParams {

	return &PostUserChecksessionParams{

		Context: ctx,
	}
}

// NewPostUserChecksessionParamsWithHTTPClient creates a new PostUserChecksessionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostUserChecksessionParamsWithHTTPClient(client *http.Client) *PostUserChecksessionParams {

	return &PostUserChecksessionParams{
		HTTPClient: client,
	}
}

/*PostUserChecksessionParams contains all the parameters to send to the API endpoint
for the post user checksession operation typically these are written to a http.Request
*/
type PostUserChecksessionParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post user checksession params
func (o *PostUserChecksessionParams) WithTimeout(timeout time.Duration) *PostUserChecksessionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post user checksession params
func (o *PostUserChecksessionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post user checksession params
func (o *PostUserChecksessionParams) WithContext(ctx context.Context) *PostUserChecksessionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post user checksession params
func (o *PostUserChecksessionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post user checksession params
func (o *PostUserChecksessionParams) WithHTTPClient(client *http.Client) *PostUserChecksessionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post user checksession params
func (o *PostUserChecksessionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostUserChecksessionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
