// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTasksBatchidParams creates a new GetTasksBatchidParams object
// with the default values initialized.
func NewGetTasksBatchidParams() *GetTasksBatchidParams {
	var ()
	return &GetTasksBatchidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTasksBatchidParamsWithTimeout creates a new GetTasksBatchidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTasksBatchidParamsWithTimeout(timeout time.Duration) *GetTasksBatchidParams {
	var ()
	return &GetTasksBatchidParams{

		timeout: timeout,
	}
}

// NewGetTasksBatchidParamsWithContext creates a new GetTasksBatchidParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTasksBatchidParamsWithContext(ctx context.Context) *GetTasksBatchidParams {
	var ()
	return &GetTasksBatchidParams{

		Context: ctx,
	}
}

// NewGetTasksBatchidParamsWithHTTPClient creates a new GetTasksBatchidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTasksBatchidParamsWithHTTPClient(client *http.Client) *GetTasksBatchidParams {
	var ()
	return &GetTasksBatchidParams{
		HTTPClient: client,
	}
}

/*GetTasksBatchidParams contains all the parameters to send to the API endpoint
for the get tasks batchid operation typically these are written to a http.Request
*/
type GetTasksBatchidParams struct {

	/*BatchID*/
	BatchID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get tasks batchid params
func (o *GetTasksBatchidParams) WithTimeout(timeout time.Duration) *GetTasksBatchidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tasks batchid params
func (o *GetTasksBatchidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tasks batchid params
func (o *GetTasksBatchidParams) WithContext(ctx context.Context) *GetTasksBatchidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tasks batchid params
func (o *GetTasksBatchidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tasks batchid params
func (o *GetTasksBatchidParams) WithHTTPClient(client *http.Client) *GetTasksBatchidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tasks batchid params
func (o *GetTasksBatchidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBatchID adds the batchID to the get tasks batchid params
func (o *GetTasksBatchidParams) WithBatchID(batchID string) *GetTasksBatchidParams {
	o.SetBatchID(batchID)
	return o
}

// SetBatchID adds the batchId to the get tasks batchid params
func (o *GetTasksBatchidParams) SetBatchID(batchID string) {
	o.BatchID = batchID
}

// WriteToRequest writes these params to a swagger request
func (o *GetTasksBatchidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param batchId
	if err := r.SetPathParam("batchId", o.BatchID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
