// Code generated by go-swagger; DO NOT EDIT.

package simulation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSimulationDevicesParams creates a new GetSimulationDevicesParams object
// with the default values initialized.
func NewGetSimulationDevicesParams() *GetSimulationDevicesParams {
	var ()
	return &GetSimulationDevicesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSimulationDevicesParamsWithTimeout creates a new GetSimulationDevicesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSimulationDevicesParamsWithTimeout(timeout time.Duration) *GetSimulationDevicesParams {
	var ()
	return &GetSimulationDevicesParams{

		timeout: timeout,
	}
}

// NewGetSimulationDevicesParamsWithContext creates a new GetSimulationDevicesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSimulationDevicesParamsWithContext(ctx context.Context) *GetSimulationDevicesParams {
	var ()
	return &GetSimulationDevicesParams{

		Context: ctx,
	}
}

// NewGetSimulationDevicesParamsWithHTTPClient creates a new GetSimulationDevicesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSimulationDevicesParamsWithHTTPClient(client *http.Client) *GetSimulationDevicesParams {
	var ()
	return &GetSimulationDevicesParams{
		HTTPClient: client,
	}
}

/*GetSimulationDevicesParams contains all the parameters to send to the API endpoint
for the get simulation devices operation typically these are written to a http.Request
*/
type GetSimulationDevicesParams struct {

	/*XAuthToken
	  Token for user authorization.

	*/
	XAuthToken *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get simulation devices params
func (o *GetSimulationDevicesParams) WithTimeout(timeout time.Duration) *GetSimulationDevicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get simulation devices params
func (o *GetSimulationDevicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get simulation devices params
func (o *GetSimulationDevicesParams) WithContext(ctx context.Context) *GetSimulationDevicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get simulation devices params
func (o *GetSimulationDevicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get simulation devices params
func (o *GetSimulationDevicesParams) WithHTTPClient(client *http.Client) *GetSimulationDevicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get simulation devices params
func (o *GetSimulationDevicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the get simulation devices params
func (o *GetSimulationDevicesParams) WithXAuthToken(xAuthToken *string) *GetSimulationDevicesParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the get simulation devices params
func (o *GetSimulationDevicesParams) SetXAuthToken(xAuthToken *string) {
	o.XAuthToken = xAuthToken
}

// WriteToRequest writes these params to a swagger request
func (o *GetSimulationDevicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XAuthToken != nil {

		// header param x-auth-token
		if err := r.SetHeaderParam("x-auth-token", *o.XAuthToken); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
