// Code generated by go-swagger; DO NOT EDIT.

package c_r_m

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new c r m API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for c r m API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetCrmRoles(params *GetCrmRolesParams, authInfo runtime.ClientAuthInfoWriter) (*GetCrmRolesOK, error)

	GetCrmServiceplans(params *GetCrmServiceplansParams, authInfo runtime.ClientAuthInfoWriter) (*GetCrmServiceplansOK, error)

	PostCrmClients(params *PostCrmClientsParams, authInfo runtime.ClientAuthInfoWriter) (*PostCrmClientsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetCrmRoles gets c r m admin users
*/
func (a *Client) GetCrmRoles(params *GetCrmRolesParams, authInfo runtime.ClientAuthInfoWriter) (*GetCrmRolesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCrmRolesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getCrmRoles",
		Method:             "GET",
		PathPattern:        "/crm/roles",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetCrmRolesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetCrmRolesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getCrmRoles: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetCrmServiceplans gets c r m service plans
*/
func (a *Client) GetCrmServiceplans(params *GetCrmServiceplansParams, authInfo runtime.ClientAuthInfoWriter) (*GetCrmServiceplansOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCrmServiceplansParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getCrmServiceplans",
		Method:             "GET",
		PathPattern:        "/crm/service-plans",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetCrmServiceplansReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetCrmServiceplansOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getCrmServiceplans: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PostCrmClients creates c r m client
*/
func (a *Client) PostCrmClients(params *PostCrmClientsParams, authInfo runtime.ClientAuthInfoWriter) (*PostCrmClientsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostCrmClientsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "postCrmClients",
		Method:             "POST",
		PathPattern:        "/crm/clients",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostCrmClientsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostCrmClientsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for postCrmClients: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
