// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateSite create site
// swagger:model CreateSite
type CreateSite struct {

	// Address of the site.
	Address string `json:"address,omitempty"`

	// Email of the contact person.
	ContactEmail string `json:"contactEmail,omitempty"`

	// Name of the contact person.
	ContactName string `json:"contactName,omitempty"`

	// Phone number of the contact person.
	ContactPhone string `json:"contactPhone,omitempty"`

	// Site elevation without structure height.
	Elevation float64 `json:"elevation,omitempty"`

	// Site structure height.
	Height float64 `json:"height,omitempty"`

	// location
	Location *CreateSiteLocation `json:"location,omitempty"`

	// Name of the site.
	// Required: true
	Name *string `json:"name"`

	// Any additional site description.
	Note string `json:"note,omitempty"`

	// ID of the parent site (deprecated).
	ParentSiteID string `json:"parentSiteId,omitempty"`

	// Location of regulation.
	// Enum: [XX XY AF AX AL DZ AS AD AO AI AQ AG AR AM AW AU AT AZ BS BH BD BB BY BE BZ BJ BM BT BO BQ BA BW BV BR IO BN BG BF BI CV KH CM CA KY CF TD CL CN CX CC CO KM CK CR CI HR CW CY CZ CD DK DJ DM DO EC EG SV GQ ER EE SZ ET FK FO FJ FI FR GF PF TF GA GM GE DE GH GI GR GL GD GP GU GT GG GN GW GY HT HM HN HK HU IS IN ID IQ IE IM IL IT JM JP JE JO KZ KE KI KW KG LA LV LB LS LR LY LI LT LU MO MK MG MW MY MV ML MT MH MQ MR MU YT MX FM MD MC MN ME MS MA MZ MM NA NR NP NL NC NZ NI NE NG NU NF MP NO OM PK PW PA PG PY PE PH PN PL PT PR QA KR RS SC CG RE RO RU RW BL SH KN LC MF PM VC WS SM ST SA SN SL SG SX SK SI SB SO ZA GS SS ES LK PS SR SJ SE CH TW TJ TZ TH TL TG TK TO TT TN TR TM TC TV UG UA AE GB US UY UZ VU VA VE VN VG VI WF EH YE ZM ZW]
	RegulatoryDomain string `json:"regulatoryDomain,omitempty"`

	// Type of the site.
	// Enum: [site endpoint client]
	Type *string `json:"type,omitempty"`
}

// Validate validates this create site
func (m *CreateSite) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLocation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRegulatoryDomain(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateSite) validateLocation(formats strfmt.Registry) error {

	if swag.IsZero(m.Location) { // not required
		return nil
	}

	if m.Location != nil {
		if err := m.Location.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("location")
			}
			return err
		}
	}

	return nil
}

func (m *CreateSite) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

var createSiteTypeRegulatoryDomainPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["XX","XY","AF","AX","AL","DZ","AS","AD","AO","AI","AQ","AG","AR","AM","AW","AU","AT","AZ","BS","BH","BD","BB","BY","BE","BZ","BJ","BM","BT","BO","BQ","BA","BW","BV","BR","IO","BN","BG","BF","BI","CV","KH","CM","CA","KY","CF","TD","CL","CN","CX","CC","CO","KM","CK","CR","CI","HR","CW","CY","CZ","CD","DK","DJ","DM","DO","EC","EG","SV","GQ","ER","EE","SZ","ET","FK","FO","FJ","FI","FR","GF","PF","TF","GA","GM","GE","DE","GH","GI","GR","GL","GD","GP","GU","GT","GG","GN","GW","GY","HT","HM","HN","HK","HU","IS","IN","ID","IQ","IE","IM","IL","IT","JM","JP","JE","JO","KZ","KE","KI","KW","KG","LA","LV","LB","LS","LR","LY","LI","LT","LU","MO","MK","MG","MW","MY","MV","ML","MT","MH","MQ","MR","MU","YT","MX","FM","MD","MC","MN","ME","MS","MA","MZ","MM","NA","NR","NP","NL","NC","NZ","NI","NE","NG","NU","NF","MP","NO","OM","PK","PW","PA","PG","PY","PE","PH","PN","PL","PT","PR","QA","KR","RS","SC","CG","RE","RO","RU","RW","BL","SH","KN","LC","MF","PM","VC","WS","SM","ST","SA","SN","SL","SG","SX","SK","SI","SB","SO","ZA","GS","SS","ES","LK","PS","SR","SJ","SE","CH","TW","TJ","TZ","TH","TL","TG","TK","TO","TT","TN","TR","TM","TC","TV","UG","UA","AE","GB","US","UY","UZ","VU","VA","VE","VN","VG","VI","WF","EH","YE","ZM","ZW"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		createSiteTypeRegulatoryDomainPropEnum = append(createSiteTypeRegulatoryDomainPropEnum, v)
	}
}

const (

	// CreateSiteRegulatoryDomainXX captures enum value "XX"
	CreateSiteRegulatoryDomainXX string = "XX"

	// CreateSiteRegulatoryDomainXY captures enum value "XY"
	CreateSiteRegulatoryDomainXY string = "XY"

	// CreateSiteRegulatoryDomainAF captures enum value "AF"
	CreateSiteRegulatoryDomainAF string = "AF"

	// CreateSiteRegulatoryDomainAX captures enum value "AX"
	CreateSiteRegulatoryDomainAX string = "AX"

	// CreateSiteRegulatoryDomainAL captures enum value "AL"
	CreateSiteRegulatoryDomainAL string = "AL"

	// CreateSiteRegulatoryDomainDZ captures enum value "DZ"
	CreateSiteRegulatoryDomainDZ string = "DZ"

	// CreateSiteRegulatoryDomainAS captures enum value "AS"
	CreateSiteRegulatoryDomainAS string = "AS"

	// CreateSiteRegulatoryDomainAD captures enum value "AD"
	CreateSiteRegulatoryDomainAD string = "AD"

	// CreateSiteRegulatoryDomainAO captures enum value "AO"
	CreateSiteRegulatoryDomainAO string = "AO"

	// CreateSiteRegulatoryDomainAI captures enum value "AI"
	CreateSiteRegulatoryDomainAI string = "AI"

	// CreateSiteRegulatoryDomainAQ captures enum value "AQ"
	CreateSiteRegulatoryDomainAQ string = "AQ"

	// CreateSiteRegulatoryDomainAG captures enum value "AG"
	CreateSiteRegulatoryDomainAG string = "AG"

	// CreateSiteRegulatoryDomainAR captures enum value "AR"
	CreateSiteRegulatoryDomainAR string = "AR"

	// CreateSiteRegulatoryDomainAM captures enum value "AM"
	CreateSiteRegulatoryDomainAM string = "AM"

	// CreateSiteRegulatoryDomainAW captures enum value "AW"
	CreateSiteRegulatoryDomainAW string = "AW"

	// CreateSiteRegulatoryDomainAU captures enum value "AU"
	CreateSiteRegulatoryDomainAU string = "AU"

	// CreateSiteRegulatoryDomainAT captures enum value "AT"
	CreateSiteRegulatoryDomainAT string = "AT"

	// CreateSiteRegulatoryDomainAZ captures enum value "AZ"
	CreateSiteRegulatoryDomainAZ string = "AZ"

	// CreateSiteRegulatoryDomainBS captures enum value "BS"
	CreateSiteRegulatoryDomainBS string = "BS"

	// CreateSiteRegulatoryDomainBH captures enum value "BH"
	CreateSiteRegulatoryDomainBH string = "BH"

	// CreateSiteRegulatoryDomainBD captures enum value "BD"
	CreateSiteRegulatoryDomainBD string = "BD"

	// CreateSiteRegulatoryDomainBB captures enum value "BB"
	CreateSiteRegulatoryDomainBB string = "BB"

	// CreateSiteRegulatoryDomainBY captures enum value "BY"
	CreateSiteRegulatoryDomainBY string = "BY"

	// CreateSiteRegulatoryDomainBE captures enum value "BE"
	CreateSiteRegulatoryDomainBE string = "BE"

	// CreateSiteRegulatoryDomainBZ captures enum value "BZ"
	CreateSiteRegulatoryDomainBZ string = "BZ"

	// CreateSiteRegulatoryDomainBJ captures enum value "BJ"
	CreateSiteRegulatoryDomainBJ string = "BJ"

	// CreateSiteRegulatoryDomainBM captures enum value "BM"
	CreateSiteRegulatoryDomainBM string = "BM"

	// CreateSiteRegulatoryDomainBT captures enum value "BT"
	CreateSiteRegulatoryDomainBT string = "BT"

	// CreateSiteRegulatoryDomainBO captures enum value "BO"
	CreateSiteRegulatoryDomainBO string = "BO"

	// CreateSiteRegulatoryDomainBQ captures enum value "BQ"
	CreateSiteRegulatoryDomainBQ string = "BQ"

	// CreateSiteRegulatoryDomainBA captures enum value "BA"
	CreateSiteRegulatoryDomainBA string = "BA"

	// CreateSiteRegulatoryDomainBW captures enum value "BW"
	CreateSiteRegulatoryDomainBW string = "BW"

	// CreateSiteRegulatoryDomainBV captures enum value "BV"
	CreateSiteRegulatoryDomainBV string = "BV"

	// CreateSiteRegulatoryDomainBR captures enum value "BR"
	CreateSiteRegulatoryDomainBR string = "BR"

	// CreateSiteRegulatoryDomainIO captures enum value "IO"
	CreateSiteRegulatoryDomainIO string = "IO"

	// CreateSiteRegulatoryDomainBN captures enum value "BN"
	CreateSiteRegulatoryDomainBN string = "BN"

	// CreateSiteRegulatoryDomainBG captures enum value "BG"
	CreateSiteRegulatoryDomainBG string = "BG"

	// CreateSiteRegulatoryDomainBF captures enum value "BF"
	CreateSiteRegulatoryDomainBF string = "BF"

	// CreateSiteRegulatoryDomainBI captures enum value "BI"
	CreateSiteRegulatoryDomainBI string = "BI"

	// CreateSiteRegulatoryDomainCV captures enum value "CV"
	CreateSiteRegulatoryDomainCV string = "CV"

	// CreateSiteRegulatoryDomainKH captures enum value "KH"
	CreateSiteRegulatoryDomainKH string = "KH"

	// CreateSiteRegulatoryDomainCM captures enum value "CM"
	CreateSiteRegulatoryDomainCM string = "CM"

	// CreateSiteRegulatoryDomainCA captures enum value "CA"
	CreateSiteRegulatoryDomainCA string = "CA"

	// CreateSiteRegulatoryDomainKY captures enum value "KY"
	CreateSiteRegulatoryDomainKY string = "KY"

	// CreateSiteRegulatoryDomainCF captures enum value "CF"
	CreateSiteRegulatoryDomainCF string = "CF"

	// CreateSiteRegulatoryDomainTD captures enum value "TD"
	CreateSiteRegulatoryDomainTD string = "TD"

	// CreateSiteRegulatoryDomainCL captures enum value "CL"
	CreateSiteRegulatoryDomainCL string = "CL"

	// CreateSiteRegulatoryDomainCN captures enum value "CN"
	CreateSiteRegulatoryDomainCN string = "CN"

	// CreateSiteRegulatoryDomainCX captures enum value "CX"
	CreateSiteRegulatoryDomainCX string = "CX"

	// CreateSiteRegulatoryDomainCC captures enum value "CC"
	CreateSiteRegulatoryDomainCC string = "CC"

	// CreateSiteRegulatoryDomainCO captures enum value "CO"
	CreateSiteRegulatoryDomainCO string = "CO"

	// CreateSiteRegulatoryDomainKM captures enum value "KM"
	CreateSiteRegulatoryDomainKM string = "KM"

	// CreateSiteRegulatoryDomainCK captures enum value "CK"
	CreateSiteRegulatoryDomainCK string = "CK"

	// CreateSiteRegulatoryDomainCR captures enum value "CR"
	CreateSiteRegulatoryDomainCR string = "CR"

	// CreateSiteRegulatoryDomainCI captures enum value "CI"
	CreateSiteRegulatoryDomainCI string = "CI"

	// CreateSiteRegulatoryDomainHR captures enum value "HR"
	CreateSiteRegulatoryDomainHR string = "HR"

	// CreateSiteRegulatoryDomainCW captures enum value "CW"
	CreateSiteRegulatoryDomainCW string = "CW"

	// CreateSiteRegulatoryDomainCY captures enum value "CY"
	CreateSiteRegulatoryDomainCY string = "CY"

	// CreateSiteRegulatoryDomainCZ captures enum value "CZ"
	CreateSiteRegulatoryDomainCZ string = "CZ"

	// CreateSiteRegulatoryDomainCD captures enum value "CD"
	CreateSiteRegulatoryDomainCD string = "CD"

	// CreateSiteRegulatoryDomainDK captures enum value "DK"
	CreateSiteRegulatoryDomainDK string = "DK"

	// CreateSiteRegulatoryDomainDJ captures enum value "DJ"
	CreateSiteRegulatoryDomainDJ string = "DJ"

	// CreateSiteRegulatoryDomainDM captures enum value "DM"
	CreateSiteRegulatoryDomainDM string = "DM"

	// CreateSiteRegulatoryDomainDO captures enum value "DO"
	CreateSiteRegulatoryDomainDO string = "DO"

	// CreateSiteRegulatoryDomainEC captures enum value "EC"
	CreateSiteRegulatoryDomainEC string = "EC"

	// CreateSiteRegulatoryDomainEG captures enum value "EG"
	CreateSiteRegulatoryDomainEG string = "EG"

	// CreateSiteRegulatoryDomainSV captures enum value "SV"
	CreateSiteRegulatoryDomainSV string = "SV"

	// CreateSiteRegulatoryDomainGQ captures enum value "GQ"
	CreateSiteRegulatoryDomainGQ string = "GQ"

	// CreateSiteRegulatoryDomainER captures enum value "ER"
	CreateSiteRegulatoryDomainER string = "ER"

	// CreateSiteRegulatoryDomainEE captures enum value "EE"
	CreateSiteRegulatoryDomainEE string = "EE"

	// CreateSiteRegulatoryDomainSZ captures enum value "SZ"
	CreateSiteRegulatoryDomainSZ string = "SZ"

	// CreateSiteRegulatoryDomainET captures enum value "ET"
	CreateSiteRegulatoryDomainET string = "ET"

	// CreateSiteRegulatoryDomainFK captures enum value "FK"
	CreateSiteRegulatoryDomainFK string = "FK"

	// CreateSiteRegulatoryDomainFO captures enum value "FO"
	CreateSiteRegulatoryDomainFO string = "FO"

	// CreateSiteRegulatoryDomainFJ captures enum value "FJ"
	CreateSiteRegulatoryDomainFJ string = "FJ"

	// CreateSiteRegulatoryDomainFI captures enum value "FI"
	CreateSiteRegulatoryDomainFI string = "FI"

	// CreateSiteRegulatoryDomainFR captures enum value "FR"
	CreateSiteRegulatoryDomainFR string = "FR"

	// CreateSiteRegulatoryDomainGF captures enum value "GF"
	CreateSiteRegulatoryDomainGF string = "GF"

	// CreateSiteRegulatoryDomainPF captures enum value "PF"
	CreateSiteRegulatoryDomainPF string = "PF"

	// CreateSiteRegulatoryDomainTF captures enum value "TF"
	CreateSiteRegulatoryDomainTF string = "TF"

	// CreateSiteRegulatoryDomainGA captures enum value "GA"
	CreateSiteRegulatoryDomainGA string = "GA"

	// CreateSiteRegulatoryDomainGM captures enum value "GM"
	CreateSiteRegulatoryDomainGM string = "GM"

	// CreateSiteRegulatoryDomainGE captures enum value "GE"
	CreateSiteRegulatoryDomainGE string = "GE"

	// CreateSiteRegulatoryDomainDE captures enum value "DE"
	CreateSiteRegulatoryDomainDE string = "DE"

	// CreateSiteRegulatoryDomainGH captures enum value "GH"
	CreateSiteRegulatoryDomainGH string = "GH"

	// CreateSiteRegulatoryDomainGI captures enum value "GI"
	CreateSiteRegulatoryDomainGI string = "GI"

	// CreateSiteRegulatoryDomainGR captures enum value "GR"
	CreateSiteRegulatoryDomainGR string = "GR"

	// CreateSiteRegulatoryDomainGL captures enum value "GL"
	CreateSiteRegulatoryDomainGL string = "GL"

	// CreateSiteRegulatoryDomainGD captures enum value "GD"
	CreateSiteRegulatoryDomainGD string = "GD"

	// CreateSiteRegulatoryDomainGP captures enum value "GP"
	CreateSiteRegulatoryDomainGP string = "GP"

	// CreateSiteRegulatoryDomainGU captures enum value "GU"
	CreateSiteRegulatoryDomainGU string = "GU"

	// CreateSiteRegulatoryDomainGT captures enum value "GT"
	CreateSiteRegulatoryDomainGT string = "GT"

	// CreateSiteRegulatoryDomainGG captures enum value "GG"
	CreateSiteRegulatoryDomainGG string = "GG"

	// CreateSiteRegulatoryDomainGN captures enum value "GN"
	CreateSiteRegulatoryDomainGN string = "GN"

	// CreateSiteRegulatoryDomainGW captures enum value "GW"
	CreateSiteRegulatoryDomainGW string = "GW"

	// CreateSiteRegulatoryDomainGY captures enum value "GY"
	CreateSiteRegulatoryDomainGY string = "GY"

	// CreateSiteRegulatoryDomainHT captures enum value "HT"
	CreateSiteRegulatoryDomainHT string = "HT"

	// CreateSiteRegulatoryDomainHM captures enum value "HM"
	CreateSiteRegulatoryDomainHM string = "HM"

	// CreateSiteRegulatoryDomainHN captures enum value "HN"
	CreateSiteRegulatoryDomainHN string = "HN"

	// CreateSiteRegulatoryDomainHK captures enum value "HK"
	CreateSiteRegulatoryDomainHK string = "HK"

	// CreateSiteRegulatoryDomainHU captures enum value "HU"
	CreateSiteRegulatoryDomainHU string = "HU"

	// CreateSiteRegulatoryDomainIS captures enum value "IS"
	CreateSiteRegulatoryDomainIS string = "IS"

	// CreateSiteRegulatoryDomainIN captures enum value "IN"
	CreateSiteRegulatoryDomainIN string = "IN"

	// CreateSiteRegulatoryDomainID captures enum value "ID"
	CreateSiteRegulatoryDomainID string = "ID"

	// CreateSiteRegulatoryDomainIQ captures enum value "IQ"
	CreateSiteRegulatoryDomainIQ string = "IQ"

	// CreateSiteRegulatoryDomainIE captures enum value "IE"
	CreateSiteRegulatoryDomainIE string = "IE"

	// CreateSiteRegulatoryDomainIM captures enum value "IM"
	CreateSiteRegulatoryDomainIM string = "IM"

	// CreateSiteRegulatoryDomainIL captures enum value "IL"
	CreateSiteRegulatoryDomainIL string = "IL"

	// CreateSiteRegulatoryDomainIT captures enum value "IT"
	CreateSiteRegulatoryDomainIT string = "IT"

	// CreateSiteRegulatoryDomainJM captures enum value "JM"
	CreateSiteRegulatoryDomainJM string = "JM"

	// CreateSiteRegulatoryDomainJP captures enum value "JP"
	CreateSiteRegulatoryDomainJP string = "JP"

	// CreateSiteRegulatoryDomainJE captures enum value "JE"
	CreateSiteRegulatoryDomainJE string = "JE"

	// CreateSiteRegulatoryDomainJO captures enum value "JO"
	CreateSiteRegulatoryDomainJO string = "JO"

	// CreateSiteRegulatoryDomainKZ captures enum value "KZ"
	CreateSiteRegulatoryDomainKZ string = "KZ"

	// CreateSiteRegulatoryDomainKE captures enum value "KE"
	CreateSiteRegulatoryDomainKE string = "KE"

	// CreateSiteRegulatoryDomainKI captures enum value "KI"
	CreateSiteRegulatoryDomainKI string = "KI"

	// CreateSiteRegulatoryDomainKW captures enum value "KW"
	CreateSiteRegulatoryDomainKW string = "KW"

	// CreateSiteRegulatoryDomainKG captures enum value "KG"
	CreateSiteRegulatoryDomainKG string = "KG"

	// CreateSiteRegulatoryDomainLA captures enum value "LA"
	CreateSiteRegulatoryDomainLA string = "LA"

	// CreateSiteRegulatoryDomainLV captures enum value "LV"
	CreateSiteRegulatoryDomainLV string = "LV"

	// CreateSiteRegulatoryDomainLB captures enum value "LB"
	CreateSiteRegulatoryDomainLB string = "LB"

	// CreateSiteRegulatoryDomainLS captures enum value "LS"
	CreateSiteRegulatoryDomainLS string = "LS"

	// CreateSiteRegulatoryDomainLR captures enum value "LR"
	CreateSiteRegulatoryDomainLR string = "LR"

	// CreateSiteRegulatoryDomainLY captures enum value "LY"
	CreateSiteRegulatoryDomainLY string = "LY"

	// CreateSiteRegulatoryDomainLI captures enum value "LI"
	CreateSiteRegulatoryDomainLI string = "LI"

	// CreateSiteRegulatoryDomainLT captures enum value "LT"
	CreateSiteRegulatoryDomainLT string = "LT"

	// CreateSiteRegulatoryDomainLU captures enum value "LU"
	CreateSiteRegulatoryDomainLU string = "LU"

	// CreateSiteRegulatoryDomainMO captures enum value "MO"
	CreateSiteRegulatoryDomainMO string = "MO"

	// CreateSiteRegulatoryDomainMK captures enum value "MK"
	CreateSiteRegulatoryDomainMK string = "MK"

	// CreateSiteRegulatoryDomainMG captures enum value "MG"
	CreateSiteRegulatoryDomainMG string = "MG"

	// CreateSiteRegulatoryDomainMW captures enum value "MW"
	CreateSiteRegulatoryDomainMW string = "MW"

	// CreateSiteRegulatoryDomainMY captures enum value "MY"
	CreateSiteRegulatoryDomainMY string = "MY"

	// CreateSiteRegulatoryDomainMV captures enum value "MV"
	CreateSiteRegulatoryDomainMV string = "MV"

	// CreateSiteRegulatoryDomainML captures enum value "ML"
	CreateSiteRegulatoryDomainML string = "ML"

	// CreateSiteRegulatoryDomainMT captures enum value "MT"
	CreateSiteRegulatoryDomainMT string = "MT"

	// CreateSiteRegulatoryDomainMH captures enum value "MH"
	CreateSiteRegulatoryDomainMH string = "MH"

	// CreateSiteRegulatoryDomainMQ captures enum value "MQ"
	CreateSiteRegulatoryDomainMQ string = "MQ"

	// CreateSiteRegulatoryDomainMR captures enum value "MR"
	CreateSiteRegulatoryDomainMR string = "MR"

	// CreateSiteRegulatoryDomainMU captures enum value "MU"
	CreateSiteRegulatoryDomainMU string = "MU"

	// CreateSiteRegulatoryDomainYT captures enum value "YT"
	CreateSiteRegulatoryDomainYT string = "YT"

	// CreateSiteRegulatoryDomainMX captures enum value "MX"
	CreateSiteRegulatoryDomainMX string = "MX"

	// CreateSiteRegulatoryDomainFM captures enum value "FM"
	CreateSiteRegulatoryDomainFM string = "FM"

	// CreateSiteRegulatoryDomainMD captures enum value "MD"
	CreateSiteRegulatoryDomainMD string = "MD"

	// CreateSiteRegulatoryDomainMC captures enum value "MC"
	CreateSiteRegulatoryDomainMC string = "MC"

	// CreateSiteRegulatoryDomainMN captures enum value "MN"
	CreateSiteRegulatoryDomainMN string = "MN"

	// CreateSiteRegulatoryDomainME captures enum value "ME"
	CreateSiteRegulatoryDomainME string = "ME"

	// CreateSiteRegulatoryDomainMS captures enum value "MS"
	CreateSiteRegulatoryDomainMS string = "MS"

	// CreateSiteRegulatoryDomainMA captures enum value "MA"
	CreateSiteRegulatoryDomainMA string = "MA"

	// CreateSiteRegulatoryDomainMZ captures enum value "MZ"
	CreateSiteRegulatoryDomainMZ string = "MZ"

	// CreateSiteRegulatoryDomainMM captures enum value "MM"
	CreateSiteRegulatoryDomainMM string = "MM"

	// CreateSiteRegulatoryDomainNA captures enum value "NA"
	CreateSiteRegulatoryDomainNA string = "NA"

	// CreateSiteRegulatoryDomainNR captures enum value "NR"
	CreateSiteRegulatoryDomainNR string = "NR"

	// CreateSiteRegulatoryDomainNP captures enum value "NP"
	CreateSiteRegulatoryDomainNP string = "NP"

	// CreateSiteRegulatoryDomainNL captures enum value "NL"
	CreateSiteRegulatoryDomainNL string = "NL"

	// CreateSiteRegulatoryDomainNC captures enum value "NC"
	CreateSiteRegulatoryDomainNC string = "NC"

	// CreateSiteRegulatoryDomainNZ captures enum value "NZ"
	CreateSiteRegulatoryDomainNZ string = "NZ"

	// CreateSiteRegulatoryDomainNI captures enum value "NI"
	CreateSiteRegulatoryDomainNI string = "NI"

	// CreateSiteRegulatoryDomainNE captures enum value "NE"
	CreateSiteRegulatoryDomainNE string = "NE"

	// CreateSiteRegulatoryDomainNG captures enum value "NG"
	CreateSiteRegulatoryDomainNG string = "NG"

	// CreateSiteRegulatoryDomainNU captures enum value "NU"
	CreateSiteRegulatoryDomainNU string = "NU"

	// CreateSiteRegulatoryDomainNF captures enum value "NF"
	CreateSiteRegulatoryDomainNF string = "NF"

	// CreateSiteRegulatoryDomainMP captures enum value "MP"
	CreateSiteRegulatoryDomainMP string = "MP"

	// CreateSiteRegulatoryDomainNO captures enum value "NO"
	CreateSiteRegulatoryDomainNO string = "NO"

	// CreateSiteRegulatoryDomainOM captures enum value "OM"
	CreateSiteRegulatoryDomainOM string = "OM"

	// CreateSiteRegulatoryDomainPK captures enum value "PK"
	CreateSiteRegulatoryDomainPK string = "PK"

	// CreateSiteRegulatoryDomainPW captures enum value "PW"
	CreateSiteRegulatoryDomainPW string = "PW"

	// CreateSiteRegulatoryDomainPA captures enum value "PA"
	CreateSiteRegulatoryDomainPA string = "PA"

	// CreateSiteRegulatoryDomainPG captures enum value "PG"
	CreateSiteRegulatoryDomainPG string = "PG"

	// CreateSiteRegulatoryDomainPY captures enum value "PY"
	CreateSiteRegulatoryDomainPY string = "PY"

	// CreateSiteRegulatoryDomainPE captures enum value "PE"
	CreateSiteRegulatoryDomainPE string = "PE"

	// CreateSiteRegulatoryDomainPH captures enum value "PH"
	CreateSiteRegulatoryDomainPH string = "PH"

	// CreateSiteRegulatoryDomainPN captures enum value "PN"
	CreateSiteRegulatoryDomainPN string = "PN"

	// CreateSiteRegulatoryDomainPL captures enum value "PL"
	CreateSiteRegulatoryDomainPL string = "PL"

	// CreateSiteRegulatoryDomainPT captures enum value "PT"
	CreateSiteRegulatoryDomainPT string = "PT"

	// CreateSiteRegulatoryDomainPR captures enum value "PR"
	CreateSiteRegulatoryDomainPR string = "PR"

	// CreateSiteRegulatoryDomainQA captures enum value "QA"
	CreateSiteRegulatoryDomainQA string = "QA"

	// CreateSiteRegulatoryDomainKR captures enum value "KR"
	CreateSiteRegulatoryDomainKR string = "KR"

	// CreateSiteRegulatoryDomainRS captures enum value "RS"
	CreateSiteRegulatoryDomainRS string = "RS"

	// CreateSiteRegulatoryDomainSC captures enum value "SC"
	CreateSiteRegulatoryDomainSC string = "SC"

	// CreateSiteRegulatoryDomainCG captures enum value "CG"
	CreateSiteRegulatoryDomainCG string = "CG"

	// CreateSiteRegulatoryDomainRE captures enum value "RE"
	CreateSiteRegulatoryDomainRE string = "RE"

	// CreateSiteRegulatoryDomainRO captures enum value "RO"
	CreateSiteRegulatoryDomainRO string = "RO"

	// CreateSiteRegulatoryDomainRU captures enum value "RU"
	CreateSiteRegulatoryDomainRU string = "RU"

	// CreateSiteRegulatoryDomainRW captures enum value "RW"
	CreateSiteRegulatoryDomainRW string = "RW"

	// CreateSiteRegulatoryDomainBL captures enum value "BL"
	CreateSiteRegulatoryDomainBL string = "BL"

	// CreateSiteRegulatoryDomainSH captures enum value "SH"
	CreateSiteRegulatoryDomainSH string = "SH"

	// CreateSiteRegulatoryDomainKN captures enum value "KN"
	CreateSiteRegulatoryDomainKN string = "KN"

	// CreateSiteRegulatoryDomainLC captures enum value "LC"
	CreateSiteRegulatoryDomainLC string = "LC"

	// CreateSiteRegulatoryDomainMF captures enum value "MF"
	CreateSiteRegulatoryDomainMF string = "MF"

	// CreateSiteRegulatoryDomainPM captures enum value "PM"
	CreateSiteRegulatoryDomainPM string = "PM"

	// CreateSiteRegulatoryDomainVC captures enum value "VC"
	CreateSiteRegulatoryDomainVC string = "VC"

	// CreateSiteRegulatoryDomainWS captures enum value "WS"
	CreateSiteRegulatoryDomainWS string = "WS"

	// CreateSiteRegulatoryDomainSM captures enum value "SM"
	CreateSiteRegulatoryDomainSM string = "SM"

	// CreateSiteRegulatoryDomainST captures enum value "ST"
	CreateSiteRegulatoryDomainST string = "ST"

	// CreateSiteRegulatoryDomainSA captures enum value "SA"
	CreateSiteRegulatoryDomainSA string = "SA"

	// CreateSiteRegulatoryDomainSN captures enum value "SN"
	CreateSiteRegulatoryDomainSN string = "SN"

	// CreateSiteRegulatoryDomainSL captures enum value "SL"
	CreateSiteRegulatoryDomainSL string = "SL"

	// CreateSiteRegulatoryDomainSG captures enum value "SG"
	CreateSiteRegulatoryDomainSG string = "SG"

	// CreateSiteRegulatoryDomainSX captures enum value "SX"
	CreateSiteRegulatoryDomainSX string = "SX"

	// CreateSiteRegulatoryDomainSK captures enum value "SK"
	CreateSiteRegulatoryDomainSK string = "SK"

	// CreateSiteRegulatoryDomainSI captures enum value "SI"
	CreateSiteRegulatoryDomainSI string = "SI"

	// CreateSiteRegulatoryDomainSB captures enum value "SB"
	CreateSiteRegulatoryDomainSB string = "SB"

	// CreateSiteRegulatoryDomainSO captures enum value "SO"
	CreateSiteRegulatoryDomainSO string = "SO"

	// CreateSiteRegulatoryDomainZA captures enum value "ZA"
	CreateSiteRegulatoryDomainZA string = "ZA"

	// CreateSiteRegulatoryDomainGS captures enum value "GS"
	CreateSiteRegulatoryDomainGS string = "GS"

	// CreateSiteRegulatoryDomainSS captures enum value "SS"
	CreateSiteRegulatoryDomainSS string = "SS"

	// CreateSiteRegulatoryDomainES captures enum value "ES"
	CreateSiteRegulatoryDomainES string = "ES"

	// CreateSiteRegulatoryDomainLK captures enum value "LK"
	CreateSiteRegulatoryDomainLK string = "LK"

	// CreateSiteRegulatoryDomainPS captures enum value "PS"
	CreateSiteRegulatoryDomainPS string = "PS"

	// CreateSiteRegulatoryDomainSR captures enum value "SR"
	CreateSiteRegulatoryDomainSR string = "SR"

	// CreateSiteRegulatoryDomainSJ captures enum value "SJ"
	CreateSiteRegulatoryDomainSJ string = "SJ"

	// CreateSiteRegulatoryDomainSE captures enum value "SE"
	CreateSiteRegulatoryDomainSE string = "SE"

	// CreateSiteRegulatoryDomainCH captures enum value "CH"
	CreateSiteRegulatoryDomainCH string = "CH"

	// CreateSiteRegulatoryDomainTW captures enum value "TW"
	CreateSiteRegulatoryDomainTW string = "TW"

	// CreateSiteRegulatoryDomainTJ captures enum value "TJ"
	CreateSiteRegulatoryDomainTJ string = "TJ"

	// CreateSiteRegulatoryDomainTZ captures enum value "TZ"
	CreateSiteRegulatoryDomainTZ string = "TZ"

	// CreateSiteRegulatoryDomainTH captures enum value "TH"
	CreateSiteRegulatoryDomainTH string = "TH"

	// CreateSiteRegulatoryDomainTL captures enum value "TL"
	CreateSiteRegulatoryDomainTL string = "TL"

	// CreateSiteRegulatoryDomainTG captures enum value "TG"
	CreateSiteRegulatoryDomainTG string = "TG"

	// CreateSiteRegulatoryDomainTK captures enum value "TK"
	CreateSiteRegulatoryDomainTK string = "TK"

	// CreateSiteRegulatoryDomainTO captures enum value "TO"
	CreateSiteRegulatoryDomainTO string = "TO"

	// CreateSiteRegulatoryDomainTT captures enum value "TT"
	CreateSiteRegulatoryDomainTT string = "TT"

	// CreateSiteRegulatoryDomainTN captures enum value "TN"
	CreateSiteRegulatoryDomainTN string = "TN"

	// CreateSiteRegulatoryDomainTR captures enum value "TR"
	CreateSiteRegulatoryDomainTR string = "TR"

	// CreateSiteRegulatoryDomainTM captures enum value "TM"
	CreateSiteRegulatoryDomainTM string = "TM"

	// CreateSiteRegulatoryDomainTC captures enum value "TC"
	CreateSiteRegulatoryDomainTC string = "TC"

	// CreateSiteRegulatoryDomainTV captures enum value "TV"
	CreateSiteRegulatoryDomainTV string = "TV"

	// CreateSiteRegulatoryDomainUG captures enum value "UG"
	CreateSiteRegulatoryDomainUG string = "UG"

	// CreateSiteRegulatoryDomainUA captures enum value "UA"
	CreateSiteRegulatoryDomainUA string = "UA"

	// CreateSiteRegulatoryDomainAE captures enum value "AE"
	CreateSiteRegulatoryDomainAE string = "AE"

	// CreateSiteRegulatoryDomainGB captures enum value "GB"
	CreateSiteRegulatoryDomainGB string = "GB"

	// CreateSiteRegulatoryDomainUS captures enum value "US"
	CreateSiteRegulatoryDomainUS string = "US"

	// CreateSiteRegulatoryDomainUY captures enum value "UY"
	CreateSiteRegulatoryDomainUY string = "UY"

	// CreateSiteRegulatoryDomainUZ captures enum value "UZ"
	CreateSiteRegulatoryDomainUZ string = "UZ"

	// CreateSiteRegulatoryDomainVU captures enum value "VU"
	CreateSiteRegulatoryDomainVU string = "VU"

	// CreateSiteRegulatoryDomainVA captures enum value "VA"
	CreateSiteRegulatoryDomainVA string = "VA"

	// CreateSiteRegulatoryDomainVE captures enum value "VE"
	CreateSiteRegulatoryDomainVE string = "VE"

	// CreateSiteRegulatoryDomainVN captures enum value "VN"
	CreateSiteRegulatoryDomainVN string = "VN"

	// CreateSiteRegulatoryDomainVG captures enum value "VG"
	CreateSiteRegulatoryDomainVG string = "VG"

	// CreateSiteRegulatoryDomainVI captures enum value "VI"
	CreateSiteRegulatoryDomainVI string = "VI"

	// CreateSiteRegulatoryDomainWF captures enum value "WF"
	CreateSiteRegulatoryDomainWF string = "WF"

	// CreateSiteRegulatoryDomainEH captures enum value "EH"
	CreateSiteRegulatoryDomainEH string = "EH"

	// CreateSiteRegulatoryDomainYE captures enum value "YE"
	CreateSiteRegulatoryDomainYE string = "YE"

	// CreateSiteRegulatoryDomainZM captures enum value "ZM"
	CreateSiteRegulatoryDomainZM string = "ZM"

	// CreateSiteRegulatoryDomainZW captures enum value "ZW"
	CreateSiteRegulatoryDomainZW string = "ZW"
)

// prop value enum
func (m *CreateSite) validateRegulatoryDomainEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, createSiteTypeRegulatoryDomainPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *CreateSite) validateRegulatoryDomain(formats strfmt.Registry) error {

	if swag.IsZero(m.RegulatoryDomain) { // not required
		return nil
	}

	// value enum
	if err := m.validateRegulatoryDomainEnum("regulatoryDomain", "body", m.RegulatoryDomain); err != nil {
		return err
	}

	return nil
}

var createSiteTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["site","endpoint","client"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		createSiteTypeTypePropEnum = append(createSiteTypeTypePropEnum, v)
	}
}

const (

	// CreateSiteTypeSite captures enum value "site"
	CreateSiteTypeSite string = "site"

	// CreateSiteTypeEndpoint captures enum value "endpoint"
	CreateSiteTypeEndpoint string = "endpoint"

	// CreateSiteTypeClient captures enum value "client"
	CreateSiteTypeClient string = "client"
)

// prop value enum
func (m *CreateSite) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, createSiteTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *CreateSite) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateSite) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateSite) UnmarshalBinary(b []byte) error {
	var res CreateSite
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
