// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// LocalChain1 local chain1
// swagger:model localChain1
type LocalChain1 []string

// Validate validates this local chain1
func (m LocalChain1) Validate(formats strfmt.Registry) error {
	return nil
}
