// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Model2 model 2
// swagger:model Model 2
type Model2 struct {

	// cidr
	// Required: true
	Cidr *string `json:"cidr"`

	// origin
	// Required: true
	// Enum: [dhcp slaac link-local static]
	Origin *string `json:"origin"`

	// type
	// Required: true
	// Enum: [dynamic static]
	Type *string `json:"type"`

	// version
	// Required: true
	// Enum: [v4 v6]
	Version *string `json:"version"`
}

// Validate validates this model 2
func (m *Model2) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCidr(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrigin(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Model2) validateCidr(formats strfmt.Registry) error {

	if err := validate.Required("cidr", "body", m.Cidr); err != nil {
		return err
	}

	return nil
}

var model2TypeOriginPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["dhcp","slaac","link-local","static"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		model2TypeOriginPropEnum = append(model2TypeOriginPropEnum, v)
	}
}

const (

	// Model2OriginDhcp captures enum value "dhcp"
	Model2OriginDhcp string = "dhcp"

	// Model2OriginSlaac captures enum value "slaac"
	Model2OriginSlaac string = "slaac"

	// Model2OriginLinkLocal captures enum value "link-local"
	Model2OriginLinkLocal string = "link-local"

	// Model2OriginStatic captures enum value "static"
	Model2OriginStatic string = "static"
)

// prop value enum
func (m *Model2) validateOriginEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, model2TypeOriginPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Model2) validateOrigin(formats strfmt.Registry) error {

	if err := validate.Required("origin", "body", m.Origin); err != nil {
		return err
	}

	// value enum
	if err := m.validateOriginEnum("origin", "body", *m.Origin); err != nil {
		return err
	}

	return nil
}

var model2TypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["dynamic","static"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		model2TypeTypePropEnum = append(model2TypeTypePropEnum, v)
	}
}

const (

	// Model2TypeDynamic captures enum value "dynamic"
	Model2TypeDynamic string = "dynamic"

	// Model2TypeStatic captures enum value "static"
	Model2TypeStatic string = "static"
)

// prop value enum
func (m *Model2) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, model2TypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Model2) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

var model2TypeVersionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["v4","v6"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		model2TypeVersionPropEnum = append(model2TypeVersionPropEnum, v)
	}
}

const (

	// Model2VersionV4 captures enum value "v4"
	Model2VersionV4 string = "v4"

	// Model2VersionV6 captures enum value "v6"
	Model2VersionV6 string = "v6"
)

// prop value enum
func (m *Model2) validateVersionEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, model2TypeVersionPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Model2) validateVersion(formats strfmt.Registry) error {

	if err := validate.Required("version", "body", m.Version); err != nil {
		return err
	}

	// value enum
	if err := m.validateVersionEnum("version", "body", *m.Version); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Model2) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Model2) UnmarshalBinary(b []byte) error {
	var res Model2
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
