// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Model50 model 50
// swagger:model Model 50
type Model50 struct {

	// device ids
	// Required: true
	DeviceIds DeviceIds4 `json:"deviceIds"`
}

// Validate validates this model 50
func (m *Model50) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeviceIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Model50) validateDeviceIds(formats strfmt.Registry) error {

	if err := validate.Required("deviceIds", "body", m.DeviceIds); err != nil {
		return err
	}

	if err := m.DeviceIds.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("deviceIds")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Model50) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Model50) UnmarshalBinary(b []byte) error {
	var res Model50
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
