// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// Model12 model 12
// swagger:model Model 12
type Model12 []float64

// Validate validates this model 12
func (m Model12) Validate(formats strfmt.Registry) error {
	return nil
}
