// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// TimezoneList timezone list
// swagger:model timezoneList
type TimezoneList []string

// Validate validates this timezone list
func (m TimezoneList) Validate(formats strfmt.Registry) error {
	return nil
}
