// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// UndeletedIds undeleted ids
// swagger:model undeletedIds
type UndeletedIds []string

// Validate validates this undeleted ids
func (m UndeletedIds) Validate(formats strfmt.Registry) error {
	return nil
}
